@host = http://localhost:6060
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjAyY2U0NjA2YTM5ZTI0YTgwYTgwZjZlIn0sImlhdCI6MTYxNjQxMTk2NCwiZXhwIjoxNjQ3OTQ3OTY0fQ.DCgw_r1hYQl7WQNhjhnepfrjyAFVHK8OeSPmMznLh54

POST {{host}}/trip/create HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "trip": {
    "numbers": {
      "LUB": 2
    },
    "jobs": [],
    "lane": "GB-NO",
    "userGroups": []
  }
}

###

GET {{host}}/trip/find-one
?number=1
Authorization: Bearer {{token}}

###

GET {{host}}/trip/find-all
Authorization: Bearer {{token}}