@host = http://localhost:6060
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjAyY2U0NjA2YTM5ZTI0YTgwYTgwZjZlIn0sImlhdCI6MTYxNTczMDU3MiwiZXhwIjoxNjE2MTYyNTcyfQ.lsKbKtWWGVKMAwvEDX4Y9DL1Nf-f6r-4wZIjqbFp17Q

@invToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiamRvZTRAZW1haWwuY29tIn0sImlhdCI6MTYxNTI4NTU2NiwiZXhwIjoxNjE1Mjg3MzY2fQ.6SXTYBv12V-Sw-He8_0oTgQOo70ZBe65fMxWZSs6Uy4

@acceptToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiamRvZTRAZW1haWwuY29tIn0sImlhdCI6MTYxNTI4NTU4NywiZXhwIjoxNjE1MzcxOTg3fQ.5cKXjJXjQFdJE1HVXlxLUy_lhGlKHDrgrBiWVfFwQlc

POST {{host}}/user/register HTTP/1.1
content-type: application/json
Authorization: Bearer {{acceptToken}}

{
  "name": "John Doe",
  "email": "jdoe4@email.com",
  "password": "ioj52lk34jki345",
  "userGroup": "6046909495d6370020f081fa"
}

###

POST {{host}}/user/login HTTP/1.1
content-type: application/json

{
  "email": "jdoe@email.com",
  "password": "ioj52lk34jki345"
}

###

POST {{host}}/user/invite HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "email": "jdoe4@email.com"
}

###

POST {{host}}/user/accept-invite HTTP/1.1
content-type: application/json
Authorization: Bearer {{invToken}}

{
  "email": "jdoe4@email.com",
  "token": "{{invToken}}"
}

###

POST {{host}}/user/new-invite-token HTTP/1.1
content-type: application/json

{
  "token": "{{invToken}}"
}