@host = http://localhost:6060
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjAyY2U0NjA2YTM5ZTI0YTgwYTgwZjZlIn0sImlhdCI6MTYxNDg4OTg2MCwiZXhwIjoxNjE1MzIxODYwfQ.Q6avZVpR8hu8cJPk2NnVNE3MT8lDJSIru-BH-v6qnzE

@invToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiamRvZTVAZW1haWwuY29tIn0sImlhdCI6MTYxMzY1MzQwOSwiZXhwIjoxNjEzNjU1MjA5fQ.m3LThtlFws48n1XFt-KDiEPGE1nXZKkHo9a-wizwFUQ

@acceptToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiamRvZTVAZW1haWwuY29tIn0sImlhdCI6MTYxMzY1MzQ0NiwiZXhwIjoxNjEzNzM5ODQ2fQ.n1UEzZxlAG1fH7pf7PGY19ixPDKfb4WgRXgqI4vmYeI

POST {{host}}/user/register HTTP/1.1
content-type: application/json
Authorization: Bearer {{acceptToken}}

{
  "name": "John Doe",
  "email": "jdoe5@email.com",
  "password": "ioj52lk34jki345"
}

###

POST {{host}}/user/login HTTP/1.1
content-type: application/json

{
  "email": "jdoe@email.com",
  "password": "ioj52lk34jki345"
}

###

POST {{host}}/user/invite HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "email": "jdoe5@email.com"
}

###

POST {{host}}/user/accept-invite HTTP/1.1
content-type: application/json
Authorization: Bearer {{invToken}}

{
  "email": "jdoe5@email.com",
  "token": "{{invToken}}"
}

###

POST {{host}}/user/new-invite-token HTTP/1.1
content-type: application/json

{
  "token": "{{invToken}}"
}

###

POST {{host}}/trip/create HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "tripNumber": "1"
}

###

GET {{host}}/trip/find?number=1
Authorization: Bearer {{token}}

###

POST {{host}}/job/create HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "jobNumber": "1",
  "tripNumber": "1"
}

###

GET {{host}}/job/find?number=1
Authorization: Bearer {{token}}
