POST http://localhost:6060/user/register HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "email": "some@email.com",
  "password": "ioj5i345"
}

###

POST http://localhost:6060/user/login HTTP/1.1
content-type: application/json

{
  "email": "some@email.com",
  "password": "ioj5i345"
}

###

POST http://localhost:6060/trip/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjAyYWExZjUxZWVkNmMwMDM2YmU2MWM3In0sImlhdCI6MTYxMzQ3NTkyMiwiZXhwIjoxNjEzOTA3OTIyfQ.mfwa0rmKLw_FAuY2stqU2AhR_fWIVVXshqkrYGktC0g

{
  "tripNumber": "2"
}

###

GET http://localhost:6060/trip/find?number=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjAyYWExZjUxZWVkNmMwMDM2YmU2MWM3In0sImlhdCI6MTYxMzQ3NTkyMiwiZXhwIjoxNjEzOTA3OTIyfQ.mfwa0rmKLw_FAuY2stqU2AhR_fWIVVXshqkrYGktC0g

###

POST http://localhost:6060/job/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjAyYWExZjUxZWVkNmMwMDM2YmU2MWM3In0sImlhdCI6MTYxMzQ3NTkyMiwiZXhwIjoxNjEzOTA3OTIyfQ.mfwa0rmKLw_FAuY2stqU2AhR_fWIVVXshqkrYGktC0g

{
  "jobNumber": "4",
  "tripNumber": "2"
}

###

GET http://localhost:6060/job/find?number=72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjAyYWExZjUxZWVkNmMwMDM2YmU2MWM3In0sImlhdCI6MTYxMzQ3NTkyMiwiZXhwIjoxNjEzOTA3OTIyfQ.mfwa0rmKLw_FAuY2stqU2AhR_fWIVVXshqkrYGktC0g
